/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentPartInput {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::AgentPartSource>>,
}

impl AgentPartInput {
    pub fn new(r#type: TypeEnum, name: String) -> AgentPartInput {
        AgentPartInput {
            id: None,
            r#type,
            name,
            source: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "agent")]
    Agent,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Agent
    }
}

