/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentConfigColor : Hex color code (e.g., #FF5733) or theme color (e.g., primary)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentConfigColor {
}

impl AgentConfigColor {
    /// Hex color code (e.g., #FF5733) or theme color (e.g., primary)
    pub fn new() -> AgentConfigColor {
        AgentConfigColor {
        }
    }
}

