/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Agent {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "mode")]
    pub mode: ModeEnum,
    #[serde(rename = "native", skip_serializing_if = "Option::is_none")]
    pub native: Option<bool>,
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde(rename = "topP", skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "permission")]
    pub permission: Vec<models::PermissionRule>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::SessionPromptRequestModel>>,
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(rename = "options")]
    pub options: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<i32>,
}

impl Agent {
    pub fn new(name: String, mode: ModeEnum, permission: Vec<models::PermissionRule>, options: std::collections::HashMap<String, serde_json::Value>) -> Agent {
        Agent {
            name,
            description: None,
            mode,
            native: None,
            hidden: None,
            top_p: None,
            temperature: None,
            color: None,
            permission,
            model: None,
            prompt: None,
            options,
            steps: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModeEnum {
    #[serde(rename = "subagent")]
    Subagent,
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "all")]
    All,
}

impl Default for ModeEnum {
    fn default() -> ModeEnum {
        Self::Subagent
    }
}

