/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiAuth {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "key")]
    pub key: String,
}

impl ApiAuth {
    pub fn new(r#type: TypeEnum, key: String) -> ApiAuth {
        ApiAuth {
            r#type,
            key,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "api")]
    Api,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Api
    }
}

