/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppSkills200ResponseInner {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "location")]
    pub location: String,
}

impl AppSkills200ResponseInner {
    pub fn new(name: String, description: String, location: String) -> AppSkills200ResponseInner {
        AppSkills200ResponseInner {
            name,
            description,
            location,
        }
    }
}

