/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantMessagePath {
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "root")]
    pub root: String,
}

impl AssistantMessagePath {
    pub fn new(cwd: String, root: String) -> AssistantMessagePath {
        AssistantMessagePath {
            cwd,
            root,
        }
    }
}

