/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssistantMessageTokens {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    #[serde(rename = "input")]
    pub input: f64,
    #[serde(rename = "output")]
    pub output: f64,
    #[serde(rename = "reasoning")]
    pub reasoning: f64,
    #[serde(rename = "cache")]
    pub cache: Box<models::AssistantMessageTokensCache>,
}

impl AssistantMessageTokens {
    pub fn new(input: f64, output: f64, reasoning: f64, cache: models::AssistantMessageTokensCache) -> AssistantMessageTokens {
        AssistantMessageTokens {
            total: None,
            input,
            output,
            reasoning,
            cache: Box::new(cache),
        }
    }
}

