/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestError {
    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<serde_json::Value>,
    #[serde(rename = "errors")]
    pub errors: Vec<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "success")]
    pub success: SuccessEnum,
}

impl BadRequestError {
    pub fn new(data: Option<serde_json::Value>, errors: Vec<std::collections::HashMap<String, serde_json::Value>>, success: SuccessEnum) -> BadRequestError {
        BadRequestError {
            data,
            errors,
            success,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SuccessEnum {
    #[serde(rename = "false")]
    False,
}

impl Default for SuccessEnum {
    fn default() -> SuccessEnum {
        Self::False
    }
}

