/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompactionPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "auto")]
    pub auto: bool,
}

impl CompactionPart {
    pub fn new(id: String, session_id: String, message_id: String, r#type: TypeEnum, auto: bool) -> CompactionPart {
        CompactionPart {
            id,
            session_id,
            message_id,
            r#type,
            auto,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "compaction")]
    Compaction,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Compaction
    }
}

