/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigMcpValueAnyOf {
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl ConfigMcpValueAnyOf {
    pub fn new(enabled: bool) -> ConfigMcpValueAnyOf {
        ConfigMcpValueAnyOf {
            enabled,
        }
    }
}

