/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigSkills : Additional skill folder paths
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigSkills {
    /// Additional paths to skill folders
    #[serde(rename = "paths", skip_serializing_if = "Option::is_none")]
    pub paths: Option<Vec<String>>,
    /// URLs to fetch skills from (e.g., https://example.com/.well-known/skills/)
    #[serde(rename = "urls", skip_serializing_if = "Option::is_none")]
    pub urls: Option<Vec<String>>,
}

impl ConfigSkills {
    /// Additional skill folder paths
    pub fn new() -> ConfigSkills {
        ConfigSkills {
            paths: None,
            urls: None,
        }
    }
}

