/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigMcpValue {
    /// Type of MCP server connection
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Command and arguments to run the MCP server
    #[serde(rename = "command")]
    pub command: Vec<String>,
    /// Environment variables to set when running the MCP server
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Timeout in ms for MCP server requests. Defaults to 5000 (5 seconds) if not specified.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i32>,
    /// URL of the remote MCP server
    #[serde(rename = "url")]
    pub url: String,
    /// Headers to send with the request
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "oauth", skip_serializing_if = "Option::is_none")]
    pub oauth: Option<Box<models::McpRemoteConfigOauth>>,
}

impl ConfigMcpValue {
    pub fn new(r#type: Type, command: Vec<String>, enabled: bool, url: String) -> ConfigMcpValue {
        ConfigMcpValue {
            r#type,
            command,
            environment: None,
            enabled,
            timeout: None,
            url,
            headers: None,
            oauth: None,
        }
    }
}
/// Type of MCP server connection
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "remote")]
    Remote,
}

impl Default for Type {
    fn default() -> Type {
        Self::Remote
    }
}

