/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigCompaction {
    /// Enable automatic compaction when context is full (default: true)
    #[serde(rename = "auto", skip_serializing_if = "Option::is_none")]
    pub auto: Option<bool>,
    /// Enable pruning of old tool outputs (default: true)
    #[serde(rename = "prune", skip_serializing_if = "Option::is_none")]
    pub prune: Option<bool>,
    /// Token buffer for compaction. Leaves enough window to avoid overflow during compaction.
    #[serde(rename = "reserved", skip_serializing_if = "Option::is_none")]
    pub reserved: Option<i32>,
}

impl ConfigCompaction {
    pub fn new() -> ConfigCompaction {
        ConfigCompaction {
            auto: None,
            prune: None,
            reserved: None,
        }
    }
}

