/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigExperimental {
    #[serde(rename = "disable_paste_summary", skip_serializing_if = "Option::is_none")]
    pub disable_paste_summary: Option<bool>,
    /// Enable the batch tool
    #[serde(rename = "batch_tool", skip_serializing_if = "Option::is_none")]
    pub batch_tool: Option<bool>,
    /// Enable OpenTelemetry spans for AI SDK calls (using the 'experimental_telemetry' flag)
    #[serde(rename = "openTelemetry", skip_serializing_if = "Option::is_none")]
    pub open_telemetry: Option<bool>,
    /// Tools that should only be available to primary agents.
    #[serde(rename = "primary_tools", skip_serializing_if = "Option::is_none")]
    pub primary_tools: Option<Vec<String>>,
    /// Continue the agent loop when a tool call is denied
    #[serde(rename = "continue_loop_on_deny", skip_serializing_if = "Option::is_none")]
    pub continue_loop_on_deny: Option<bool>,
    /// Timeout in milliseconds for model context protocol (MCP) requests
    #[serde(rename = "mcp_timeout", skip_serializing_if = "Option::is_none")]
    pub mcp_timeout: Option<i32>,
}

impl ConfigExperimental {
    pub fn new() -> ConfigExperimental {
        ConfigExperimental {
            disable_paste_summary: None,
            batch_tool: None,
            open_telemetry: None,
            primary_tools: None,
            continue_loop_on_deny: None,
            mcp_timeout: None,
        }
    }
}

