/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigLspAnyOfValueAnyOf {
    #[serde(rename = "disabled")]
    pub disabled: DisabledEnum,
}

impl ConfigLspAnyOfValueAnyOf {
    pub fn new(disabled: DisabledEnum) -> ConfigLspAnyOfValueAnyOf {
        ConfigLspAnyOfValueAnyOf {
            disabled,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DisabledEnum {
    #[serde(rename = "true")]
    True,
}

impl Default for DisabledEnum {
    fn default() -> DisabledEnum {
        Self::True
    }
}

