/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextOverflowError {
    #[serde(rename = "name")]
    pub name: NameEnum,
    #[serde(rename = "data")]
    pub data: Box<models::ContextOverflowErrorData>,
}

impl ContextOverflowError {
    pub fn new(name: NameEnum, data: models::ContextOverflowErrorData) -> ContextOverflowError {
        ContextOverflowError {
            name,
            data: Box::new(data),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NameEnum {
    #[serde(rename = "ContextOverflowError")]
    ContextOverflowError,
}

impl Default for NameEnum {
    fn default() -> NameEnum {
        Self::ContextOverflowError
    }
}

