/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextOverflowErrorData {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "responseBody", skip_serializing_if = "Option::is_none")]
    pub response_body: Option<String>,
}

impl ContextOverflowErrorData {
    pub fn new(message: String) -> ContextOverflowErrorData {
        ContextOverflowErrorData {
            message,
            response_body: None,
        }
    }
}

