/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventWorktreeReadyProperties {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "branch")]
    pub branch: String,
}

impl EventWorktreeReadyProperties {
    pub fn new(name: String, branch: String) -> EventWorktreeReadyProperties {
        EventWorktreeReadyProperties {
            name,
            branch,
        }
    }
}

