/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSessionCreatedProperties {
    #[serde(rename = "info")]
    pub info: Box<models::Session>,
}

impl EventSessionCreatedProperties {
    pub fn new(info: models::Session) -> EventSessionCreatedProperties {
        EventSessionCreatedProperties {
            info: Box::new(info),
        }
    }
}

