/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventGlobalDisposed {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "properties")]
    pub properties: serde_json::Value,
}

impl EventGlobalDisposed {
    pub fn new(r#type: TypeEnum, properties: serde_json::Value) -> EventGlobalDisposed {
        EventGlobalDisposed {
            r#type,
            properties,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "global.disposed")]
    GlobalDisposed,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::GlobalDisposed
    }
}

