/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventLspClientDiagnostics {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventLspClientDiagnosticsProperties>,
}

impl EventLspClientDiagnostics {
    pub fn new(r#type: Type, properties: models::EventLspClientDiagnosticsProperties) -> EventLspClientDiagnostics {
        EventLspClientDiagnostics {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "lsp.client.diagnostics")]
    LspClientDiagnostics,
}

impl Default for Type {
    fn default() -> Type {
        Self::LspClientDiagnostics
    }
}

