/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventInstallationUpdatedProperties {
    #[serde(rename = "version")]
    pub version: String,
}

impl EventInstallationUpdatedProperties {
    pub fn new(version: String) -> EventInstallationUpdatedProperties {
        EventInstallationUpdatedProperties {
            version,
        }
    }
}

