/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventTuiCommandExecuteProperties {
    #[serde(rename = "command")]
    pub command: Box<models::EventTuiCommandExecutePropertiesCommand>,
}

impl EventTuiCommandExecuteProperties {
    pub fn new(command: models::EventTuiCommandExecutePropertiesCommand) -> EventTuiCommandExecuteProperties {
        EventTuiCommandExecuteProperties {
            command: Box::new(command),
        }
    }
}

