/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPtyDeletedProperties {
    #[serde(rename = "id")]
    pub id: String,
}

impl EventPtyDeletedProperties {
    pub fn new(id: String) -> EventPtyDeletedProperties {
        EventPtyDeletedProperties {
            id,
        }
    }
}

