/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMessagePartUpdatedProperties {
    #[serde(rename = "part")]
    pub part: Box<models::Part>,
}

impl EventMessagePartUpdatedProperties {
    pub fn new(part: models::Part) -> EventMessagePartUpdatedProperties {
        EventMessagePartUpdatedProperties {
            part: Box::new(part),
        }
    }
}

