/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventQuestionReplied {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventQuestionRepliedProperties>,
}

impl EventQuestionReplied {
    pub fn new(r#type: TypeEnum, properties: models::EventQuestionRepliedProperties) -> EventQuestionReplied {
        EventQuestionReplied {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "question.replied")]
    QuestionReplied,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::QuestionReplied
    }
}

