/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventTuiSessionSelect {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::TuiSelectSessionRequest>,
}

impl EventTuiSessionSelect {
    pub fn new(r#type: Type, properties: models::TuiSelectSessionRequest) -> EventTuiSessionSelect {
        EventTuiSessionSelect {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "tui.session.select")]
    TuiSessionSelect,
}

impl Default for Type {
    fn default() -> Type {
        Self::TuiSessionSelect
    }
}

