/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventCommandExecuted {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventCommandExecutedProperties>,
}

impl EventCommandExecuted {
    pub fn new(r#type: TypeEnum, properties: models::EventCommandExecutedProperties) -> EventCommandExecuted {
        EventCommandExecuted {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "command.executed")]
    CommandExecuted,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::CommandExecuted
    }
}

