/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMessagePartDelta {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventMessagePartDeltaProperties>,
}

impl EventMessagePartDelta {
    pub fn new(r#type: TypeEnum, properties: models::EventMessagePartDeltaProperties) -> EventMessagePartDelta {
        EventMessagePartDelta {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "message.part.delta")]
    MessagePartDelta,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::MessagePartDelta
    }
}

