/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventQuestionRejectedProperties {
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "requestID")]
    pub request_id: String,
}

impl EventQuestionRejectedProperties {
    pub fn new(session_id: String, request_id: String) -> EventQuestionRejectedProperties {
        EventQuestionRejectedProperties {
            session_id,
            request_id,
        }
    }
}

