/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMcpBrowserOpenFailedProperties {
    #[serde(rename = "mcpName")]
    pub mcp_name: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl EventMcpBrowserOpenFailedProperties {
    pub fn new(mcp_name: String, url: String) -> EventMcpBrowserOpenFailedProperties {
        EventMcpBrowserOpenFailedProperties {
            mcp_name,
            url,
        }
    }
}

