/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventFileEdited {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventFileEditedProperties>,
}

impl EventFileEdited {
    pub fn new(r#type: TypeEnum, properties: models::EventFileEditedProperties) -> EventFileEdited {
        EventFileEdited {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "file.edited")]
    FileEdited,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::FileEdited
    }
}

