/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventMessageRemoved {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventMessageRemovedProperties>,
}

impl EventMessageRemoved {
    pub fn new(r#type: TypeEnum, properties: models::EventMessageRemovedProperties) -> EventMessageRemoved {
        EventMessageRemoved {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "message.removed")]
    MessageRemoved,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::MessageRemoved
    }
}

