/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventWorkspaceReadyProperties {
    #[serde(rename = "name")]
    pub name: String,
}

impl EventWorkspaceReadyProperties {
    pub fn new(name: String) -> EventWorkspaceReadyProperties {
        EventWorkspaceReadyProperties {
            name,
        }
    }
}

