/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPermissionRepliedProperties {
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "requestID")]
    pub request_id: String,
    #[serde(rename = "reply")]
    pub reply: Reply,
}

impl EventPermissionRepliedProperties {
    pub fn new(session_id: String, request_id: String, reply: Reply) -> EventPermissionRepliedProperties {
        EventPermissionRepliedProperties {
            session_id,
            request_id,
            reply,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reply {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "reject")]
    Reject,
}

impl Default for Reply {
    fn default() -> Reply {
        Self::Once
    }
}

