/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSessionCreated {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "properties")]
    pub properties: Box<models::EventSessionCreatedProperties>,
}

impl EventSessionCreated {
    pub fn new(r#type: Type, properties: models::EventSessionCreatedProperties) -> EventSessionCreated {
        EventSessionCreated {
            r#type,
            properties: Box::new(properties),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "session.created")]
    SessionCreated,
}

impl Default for Type {
    fn default() -> Type {
        Self::SessionCreated
    }
}

