/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventFileWatcherUpdatedProperties {
    #[serde(rename = "file")]
    pub file: String,
    #[serde(rename = "event")]
    pub event: EventEnum,
}

impl EventFileWatcherUpdatedProperties {
    pub fn new(file: String, event: EventEnum) -> EventFileWatcherUpdatedProperties {
        EventFileWatcherUpdatedProperties {
            file,
            event,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventEnum {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "change")]
    Change,
    #[serde(rename = "unlink")]
    Unlink,
}

impl Default for EventEnum {
    fn default() -> EventEnum {
        Self::Add
    }
}

