/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventPtyCreatedProperties {
    #[serde(rename = "info")]
    pub info: Box<models::Pty>,
}

impl EventPtyCreatedProperties {
    pub fn new(info: models::Pty) -> EventPtyCreatedProperties {
        EventPtyCreatedProperties {
            info: Box::new(info),
        }
    }
}

