/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExperimentalWorkspaceCreateRequestConfig {
    #[serde(rename = "directory")]
    pub directory: String,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
}

impl ExperimentalWorkspaceCreateRequestConfig {
    pub fn new(directory: String, r#type: TypeEnum) -> ExperimentalWorkspaceCreateRequestConfig {
        ExperimentalWorkspaceCreateRequestConfig {
            directory,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "worktree")]
    Worktree,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Worktree
    }
}

