/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExperimentalWorkspaceCreateRequest {
    #[serde(rename = "branch", deserialize_with = "Option::deserialize")]
    pub branch: Option<String>,
    #[serde(rename = "config")]
    pub config: Box<models::ExperimentalWorkspaceCreateRequestConfig>,
}

impl ExperimentalWorkspaceCreateRequest {
    pub fn new(branch: Option<String>, config: models::ExperimentalWorkspaceCreateRequestConfig) -> ExperimentalWorkspaceCreateRequest {
        ExperimentalWorkspaceCreateRequest {
            branch,
            config: Box::new(config),
        }
    }
}

