/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileNode {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "absolute")]
    pub absolute: String,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "ignored")]
    pub ignored: bool,
}

impl FileNode {
    pub fn new(name: String, path: String, absolute: String, r#type: TypeEnum, ignored: bool) -> FileNode {
        FileNode {
            name,
            path,
            absolute,
            r#type,
            ignored,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "directory")]
    Directory,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::File
    }
}

