/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileContent {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "diff", skip_serializing_if = "Option::is_none")]
    pub diff: Option<String>,
    #[serde(rename = "patch", skip_serializing_if = "Option::is_none")]
    pub patch: Option<Box<models::FileContentPatch>>,
    #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<EncodingEnum>,
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
}

impl FileContent {
    pub fn new(r#type: TypeEnum, content: String) -> FileContent {
        FileContent {
            r#type,
            content,
            diff: None,
            patch: None,
            encoding: None,
            mime_type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "text")]
    Text,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Text
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EncodingEnum {
    #[serde(rename = "base64")]
    Base64,
}

impl Default for EncodingEnum {
    fn default() -> EncodingEnum {
        Self::Base64
    }
}

