/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilePartSource {
    #[serde(rename = "text")]
    pub text: Box<models::FilePartSourceText>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "range")]
    pub range: Box<models::Range>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: i32,
    #[serde(rename = "clientName")]
    pub client_name: String,
    #[serde(rename = "uri")]
    pub uri: String,
}

impl FilePartSource {
    pub fn new(text: models::FilePartSourceText, r#type: Type, path: String, range: models::Range, name: String, kind: i32, client_name: String, uri: String) -> FilePartSource {
        FilePartSource {
            text: Box::new(text),
            r#type,
            path,
            range: Box::new(range),
            name,
            kind,
            client_name,
            uri,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "symbol")]
    Symbol,
    #[serde(rename = "resource")]
    Resource,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}

