/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDiff {
    #[serde(rename = "file")]
    pub file: String,
    #[serde(rename = "before")]
    pub before: String,
    #[serde(rename = "after")]
    pub after: String,
    #[serde(rename = "additions")]
    pub additions: f64,
    #[serde(rename = "deletions")]
    pub deletions: f64,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<StatusEnum>,
}

impl FileDiff {
    pub fn new(file: String, before: String, after: String, additions: f64, deletions: f64) -> FileDiff {
        FileDiff {
            file,
            before,
            after,
            additions,
            deletions,
            status: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEnum {
    #[serde(rename = "added")]
    Added,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "modified")]
    Modified,
}

impl Default for StatusEnum {
    fn default() -> StatusEnum {
        Self::Added
    }
}

