/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalSession {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "projectID")]
    pub project_id: String,
    #[serde(rename = "directory")]
    pub directory: String,
    #[serde(rename = "parentID", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<Box<models::SessionSummary>>,
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<Box<models::SessionShare>>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "time")]
    pub time: Box<models::SessionTime>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Vec<models::PermissionRule>>,
    #[serde(rename = "revert", skip_serializing_if = "Option::is_none")]
    pub revert: Option<Box<models::SessionRevert>>,
    #[serde(rename = "project", deserialize_with = "Option::deserialize")]
    pub project: Option<Box<models::ProjectSummary>>,
}

impl GlobalSession {
    pub fn new(id: String, slug: String, project_id: String, directory: String, title: String, version: String, time: models::SessionTime, project: Option<models::ProjectSummary>) -> GlobalSession {
        GlobalSession {
            id,
            slug,
            project_id,
            directory,
            parent_id: None,
            summary: None,
            share: None,
            title,
            version,
            time: Box::new(time),
            permission: None,
            revert: None,
            project: if let Some(x) = project {Some(Box::new(x))} else {None},
        }
    }
}

