/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalHealth200Response {
    #[serde(rename = "healthy")]
    pub healthy: HealthyEnum,
    #[serde(rename = "version")]
    pub version: String,
}

impl GlobalHealth200Response {
    pub fn new(healthy: HealthyEnum, version: String) -> GlobalHealth200Response {
        GlobalHealth200Response {
            healthy,
            version,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HealthyEnum {
    #[serde(rename = "true")]
    True,
}

impl Default for HealthyEnum {
    fn default() -> HealthyEnum {
        Self::True
    }
}

