/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LspStatus {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "root")]
    pub root: String,
    #[serde(rename = "status")]
    pub status: StatusEnum,
}

impl LspStatus {
    pub fn new(id: String, name: String, root: String, status: StatusEnum) -> LspStatus {
        LspStatus {
            id,
            name,
            root,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEnum {
    #[serde(rename = "connected")]
    Connected,
    #[serde(rename = "error")]
    Error,
}

impl Default for StatusEnum {
    fn default() -> StatusEnum {
        Self::Connected
    }
}

