/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpStatusConnected {
    #[serde(rename = "status")]
    pub status: StatusEnum,
}

impl McpStatusConnected {
    pub fn new(status: StatusEnum) -> McpStatusConnected {
        McpStatusConnected {
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEnum {
    #[serde(rename = "connected")]
    Connected,
}

impl Default for StatusEnum {
    fn default() -> StatusEnum {
        Self::Connected
    }
}

