/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpResource {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(rename = "client")]
    pub client: String,
}

impl McpResource {
    pub fn new(name: String, uri: String, client: String) -> McpResource {
        McpResource {
            name,
            uri,
            description: None,
            mime_type: None,
            client,
        }
    }
}

