/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpAuthRemove200Response {
    #[serde(rename = "success")]
    pub success: SuccessEnum,
}

impl McpAuthRemove200Response {
    pub fn new(success: SuccessEnum) -> McpAuthRemove200Response {
        McpAuthRemove200Response {
            success,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SuccessEnum {
    #[serde(rename = "true")]
    True,
}

impl Default for SuccessEnum {
    fn default() -> SuccessEnum {
        Self::True
    }
}

