/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpAuthStart200Response {
    /// URL to open in browser for authorization
    #[serde(rename = "authorizationUrl")]
    pub authorization_url: String,
}

impl McpAuthStart200Response {
    pub fn new(authorization_url: String) -> McpAuthStart200Response {
        McpAuthStart200Response {
            authorization_url,
        }
    }
}

