/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct McpStatusFailed {
    #[serde(rename = "status")]
    pub status: StatusEnum,
    #[serde(rename = "error")]
    pub error: String,
}

impl McpStatusFailed {
    pub fn new(status: StatusEnum, error: String) -> McpStatusFailed {
        McpStatusFailed {
            status,
            error,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEnum {
    #[serde(rename = "failed")]
    Failed,
}

impl Default for StatusEnum {
    fn default() -> StatusEnum {
        Self::Failed
    }
}

