/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "refresh")]
    pub refresh: String,
    #[serde(rename = "access")]
    pub access: String,
    #[serde(rename = "expires")]
    pub expires: f64,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "enterpriseUrl", skip_serializing_if = "Option::is_none")]
    pub enterprise_url: Option<String>,
}

impl OAuth {
    pub fn new(r#type: TypeEnum, refresh: String, access: String, expires: f64) -> OAuth {
        OAuth {
            r#type,
            refresh,
            access,
            expires,
            account_id: None,
            enterprise_url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "oauth")]
    Oauth,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Oauth
    }
}

