/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputFormatText {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
}

impl OutputFormatText {
    pub fn new(r#type: TypeEnum) -> OutputFormatText {
        OutputFormatText {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "text")]
    Text,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Text
    }
}

