/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputFormat {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "schema")]
    pub schema: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "retryCount", skip_serializing_if = "Option::is_none")]
    pub retry_count: Option<i32>,
}

impl OutputFormat {
    pub fn new(r#type: TypeEnum, schema: std::collections::HashMap<String, serde_json::Value>) -> OutputFormat {
        OutputFormat {
            r#type,
            schema,
            retry_count: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "json_schema")]
    JsonSchema,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Text
    }
}

