/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionConfig {
    #[serde(rename = "__originalKeys", skip_serializing_if = "Option::is_none")]
    pub __original_keys: Option<Vec<String>>,
    #[serde(rename = "read", skip_serializing_if = "Option::is_none")]
    pub read: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "edit", skip_serializing_if = "Option::is_none")]
    pub edit: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "glob", skip_serializing_if = "Option::is_none")]
    pub glob: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "grep", skip_serializing_if = "Option::is_none")]
    pub grep: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "bash", skip_serializing_if = "Option::is_none")]
    pub bash: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "task", skip_serializing_if = "Option::is_none")]
    pub task: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "external_directory", skip_serializing_if = "Option::is_none")]
    pub external_directory: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "todowrite", skip_serializing_if = "Option::is_none")]
    pub todowrite: Option<models::PermissionActionConfig>,
    #[serde(rename = "todoread", skip_serializing_if = "Option::is_none")]
    pub todoread: Option<models::PermissionActionConfig>,
    #[serde(rename = "question", skip_serializing_if = "Option::is_none")]
    pub question: Option<models::PermissionActionConfig>,
    #[serde(rename = "webfetch", skip_serializing_if = "Option::is_none")]
    pub webfetch: Option<models::PermissionActionConfig>,
    #[serde(rename = "websearch", skip_serializing_if = "Option::is_none")]
    pub websearch: Option<models::PermissionActionConfig>,
    #[serde(rename = "codesearch", skip_serializing_if = "Option::is_none")]
    pub codesearch: Option<models::PermissionActionConfig>,
    #[serde(rename = "lsp", skip_serializing_if = "Option::is_none")]
    pub lsp: Option<Box<models::PermissionRuleConfig>>,
    #[serde(rename = "doom_loop", skip_serializing_if = "Option::is_none")]
    pub doom_loop: Option<models::PermissionActionConfig>,
}

impl PermissionConfig {
    pub fn new() -> PermissionConfig {
        PermissionConfig {
            __original_keys: None,
            read: None,
            edit: None,
            glob: None,
            grep: None,
            list: None,
            bash: None,
            task: None,
            external_directory: None,
            todowrite: None,
            todoread: None,
            question: None,
            webfetch: None,
            websearch: None,
            codesearch: None,
            lsp: None,
            doom_loop: None,
        }
    }
}

