/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionReplyRequest {
    #[serde(rename = "reply")]
    pub reply: ReplyEnum,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PermissionReplyRequest {
    pub fn new(reply: ReplyEnum) -> PermissionReplyRequest {
        PermissionReplyRequest {
            reply,
            message: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReplyEnum {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "reject")]
    Reject,
}

impl Default for ReplyEnum {
    fn default() -> ReplyEnum {
        Self::Once
    }
}

