/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionRespondRequest {
    #[serde(rename = "response")]
    pub response: ResponseEnum,
}

impl PermissionRespondRequest {
    pub fn new(response: ResponseEnum) -> PermissionRespondRequest {
        PermissionRespondRequest {
            response,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResponseEnum {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "reject")]
    Reject,
}

impl Default for ResponseEnum {
    fn default() -> ResponseEnum {
        Self::Once
    }
}

