/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionRule {
    #[serde(rename = "permission")]
    pub permission: String,
    #[serde(rename = "pattern")]
    pub pattern: String,
    #[serde(rename = "action")]
    pub action: models::PermissionAction,
}

impl PermissionRule {
    pub fn new(permission: String, pattern: String, action: models::PermissionAction) -> PermissionRule {
        PermissionRule {
            permission,
            pattern,
            action,
        }
    }
}

