/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "permission")]
    pub permission: String,
    #[serde(rename = "patterns")]
    pub patterns: Vec<String>,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "always")]
    pub always: Vec<String>,
    #[serde(rename = "tool", skip_serializing_if = "Option::is_none")]
    pub tool: Option<Box<models::PermissionRequestTool>>,
}

impl PermissionRequest {
    pub fn new(id: String, session_id: String, permission: String, patterns: Vec<String>, metadata: std::collections::HashMap<String, serde_json::Value>, always: Vec<String>) -> PermissionRequest {
        PermissionRequest {
            id,
            session_id,
            permission,
            patterns,
            metadata,
            always,
            tool: None,
        }
    }
}

