/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "worktree")]
    pub worktree: String,
}

impl ProjectSummary {
    pub fn new(id: String, worktree: String) -> ProjectSummary {
        ProjectSummary {
            id,
            name: None,
            worktree,
        }
    }
}

