/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectUpdateRequestCommands {
    /// Startup script to run when creating a new workspace (worktree)
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
}

impl ProjectUpdateRequestCommands {
    pub fn new() -> ProjectUpdateRequestCommands {
        ProjectUpdateRequestCommands {
            start: None,
        }
    }
}

