/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueProvider {
    #[serde(rename = "npm")]
    pub npm: String,
    #[serde(rename = "api")]
    pub api: String,
}

impl ProviderList200ResponseAllInnerModelsValueProvider {
    pub fn new(npm: String, api: String) -> ProviderList200ResponseAllInnerModelsValueProvider {
        ProviderList200ResponseAllInnerModelsValueProvider {
            npm,
            api,
        }
    }
}

