/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueProvider {
    #[serde(rename = "npm", skip_serializing_if = "Option::is_none")]
    pub npm: Option<String>,
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
}

impl ProviderList200ResponseAllInnerModelsValueProvider {
    pub fn new() -> ProviderList200ResponseAllInnerModelsValueProvider {
        ProviderList200ResponseAllInnerModelsValueProvider {
            npm: None,
            api: None,
        }
    }
}

