/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderConfigModelsValueInterleavedAnyOf {
    #[serde(rename = "field")]
    pub field: FieldEnum,
}

impl ProviderConfigModelsValueInterleavedAnyOf {
    pub fn new(field: FieldEnum) -> ProviderConfigModelsValueInterleavedAnyOf {
        ProviderConfigModelsValueInterleavedAnyOf {
            field,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FieldEnum {
    #[serde(rename = "reasoning_content")]
    ReasoningContent,
    #[serde(rename = "reasoning_details")]
    ReasoningDetails,
}

impl Default for FieldEnum {
    fn default() -> FieldEnum {
        Self::ReasoningContent
    }
}

