/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueModalities {
    #[serde(rename = "input")]
    pub input: Vec<InputEnum>,
    #[serde(rename = "output")]
    pub output: Vec<OutputEnum>,
}

impl ProviderList200ResponseAllInnerModelsValueModalities {
    pub fn new(input: Vec<InputEnum>, output: Vec<OutputEnum>) -> ProviderList200ResponseAllInnerModelsValueModalities {
        ProviderList200ResponseAllInnerModelsValueModalities {
            input,
            output,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InputEnum {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "pdf")]
    Pdf,
}

impl Default for InputEnum {
    fn default() -> InputEnum {
        Self::Text
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OutputEnum {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "pdf")]
    Pdf,
}

impl Default for OutputEnum {
    fn default() -> OutputEnum {
        Self::Text
    }
}

