/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderList200ResponseAllInnerModelsValueLimit {
    #[serde(rename = "context")]
    pub context: f64,
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<f64>,
    #[serde(rename = "output")]
    pub output: f64,
}

impl ProviderList200ResponseAllInnerModelsValueLimit {
    pub fn new(context: f64, output: f64) -> ProviderList200ResponseAllInnerModelsValueLimit {
        ProviderList200ResponseAllInnerModelsValueLimit {
            context,
            input: None,
            output,
        }
    }
}

