/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderAuthMethod {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "label")]
    pub label: String,
}

impl ProviderAuthMethod {
    pub fn new(r#type: TypeEnum, label: String) -> ProviderAuthMethod {
        ProviderAuthMethod {
            r#type,
            label,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "oauth")]
    Oauth,
    #[serde(rename = "api")]
    Api,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Oauth
    }
}

