/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderAuthAuthorization {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "method")]
    pub method: MethodEnum,
    #[serde(rename = "instructions")]
    pub instructions: String,
}

impl ProviderAuthAuthorization {
    pub fn new(url: String, method: MethodEnum, instructions: String) -> ProviderAuthAuthorization {
        ProviderAuthAuthorization {
            url,
            method,
            instructions,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MethodEnum {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "code")]
    Code,
}

impl Default for MethodEnum {
    fn default() -> MethodEnum {
        Self::Auto
    }
}

