/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    /// Questions to ask
    #[serde(rename = "questions")]
    pub questions: Vec<models::QuestionInfo>,
    #[serde(rename = "tool", skip_serializing_if = "Option::is_none")]
    pub tool: Option<Box<models::PermissionRequestTool>>,
}

impl QuestionRequest {
    pub fn new(id: String, session_id: String, questions: Vec<models::QuestionInfo>) -> QuestionRequest {
        QuestionRequest {
            id,
            session_id,
            questions,
            tool: None,
        }
    }
}

