/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionOption {
    /// Display text (1-5 words, concise)
    #[serde(rename = "label")]
    pub label: String,
    /// Explanation of choice
    #[serde(rename = "description")]
    pub description: String,
}

impl QuestionOption {
    pub fn new(label: String, description: String) -> QuestionOption {
        QuestionOption {
            label,
            description,
        }
    }
}

