/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionReplyRequest {
    /// User answers in order of questions (each answer is an array of selected labels)
    #[serde(rename = "answers")]
    pub answers: Vec<Vec<String>>,
}

impl QuestionReplyRequest {
    pub fn new(answers: Vec<Vec<String>>) -> QuestionReplyRequest {
        QuestionReplyRequest {
            answers,
        }
    }
}

