/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuestionInfo {
    /// Complete question
    #[serde(rename = "question")]
    pub question: String,
    /// Very short label (max 30 chars)
    #[serde(rename = "header")]
    pub header: String,
    /// Available choices
    #[serde(rename = "options")]
    pub options: Vec<models::QuestionOption>,
    /// Allow selecting multiple choices
    #[serde(rename = "multiple", skip_serializing_if = "Option::is_none")]
    pub multiple: Option<bool>,
    /// Allow typing a custom answer (default: true)
    #[serde(rename = "custom", skip_serializing_if = "Option::is_none")]
    pub custom: Option<bool>,
}

impl QuestionInfo {
    pub fn new(question: String, header: String, options: Vec<models::QuestionOption>) -> QuestionInfo {
        QuestionInfo {
            question,
            header,
            options,
            multiple: None,
            custom: None,
        }
    }
}

