/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceSource {
    #[serde(rename = "text")]
    pub text: Box<models::FilePartSourceText>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "clientName")]
    pub client_name: String,
    #[serde(rename = "uri")]
    pub uri: String,
}

impl ResourceSource {
    pub fn new(text: models::FilePartSourceText, r#type: Type, client_name: String, uri: String) -> ResourceSource {
        ResourceSource {
            text: Box::new(text),
            r#type,
            client_name,
            uri,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "resource")]
    Resource,
}

impl Default for Type {
    fn default() -> Type {
        Self::Resource
    }
}

