/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionCommandRequestPartsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "mime")]
    pub mime: String,
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::FilePartSource>>,
}

impl SessionCommandRequestPartsInner {
    pub fn new(r#type: TypeEnum, mime: String, url: String) -> SessionCommandRequestPartsInner {
        SessionCommandRequestPartsInner {
            id: None,
            r#type,
            mime,
            filename: None,
            url,
            source: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "file")]
    File,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::File
    }
}

