/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionShare {
    #[serde(rename = "url")]
    pub url: String,
}

impl SessionShare {
    pub fn new(url: String) -> SessionShare {
        SessionShare {
            url,
        }
    }
}

