/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "snapshot")]
    pub snapshot: String,
}

impl SnapshotPart {
    pub fn new(id: String, session_id: String, message_id: String, r#type: TypeEnum, snapshot: String) -> SnapshotPart {
        SnapshotPart {
            id,
            session_id,
            message_id,
            r#type,
            snapshot,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "snapshot")]
    Snapshot,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Snapshot
    }
}

