/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StepFinishPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "snapshot", skip_serializing_if = "Option::is_none")]
    pub snapshot: Option<String>,
    #[serde(rename = "cost")]
    pub cost: f64,
    #[serde(rename = "tokens")]
    pub tokens: Box<models::AssistantMessageTokens>,
}

impl StepFinishPart {
    pub fn new(id: String, session_id: String, message_id: String, r#type: TypeEnum, reason: String, cost: f64, tokens: models::AssistantMessageTokens) -> StepFinishPart {
        StepFinishPart {
            id,
            session_id,
            message_id,
            r#type,
            reason,
            snapshot: None,
            cost,
            tokens: Box::new(tokens),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "step-finish")]
    StepFinish,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::StepFinish
    }
}

