/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StructuredOutputError {
    #[serde(rename = "name")]
    pub name: NameEnum,
    #[serde(rename = "data")]
    pub data: Box<models::StructuredOutputErrorData>,
}

impl StructuredOutputError {
    pub fn new(name: NameEnum, data: models::StructuredOutputErrorData) -> StructuredOutputError {
        StructuredOutputError {
            name,
            data: Box::new(data),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NameEnum {
    #[serde(rename = "StructuredOutputError")]
    StructuredOutputError,
}

impl Default for NameEnum {
    fn default() -> NameEnum {
        Self::StructuredOutputError
    }
}

