/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StructuredOutputErrorData {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "retries")]
    pub retries: f64,
}

impl StructuredOutputErrorData {
    pub fn new(message: String, retries: f64) -> StructuredOutputErrorData {
        StructuredOutputErrorData {
            message,
            retries,
        }
    }
}

