/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubtaskPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sessionID")]
    pub session_id: String,
    #[serde(rename = "messageID")]
    pub message_id: String,
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "prompt")]
    pub prompt: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::SessionPromptRequestModel>>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl SubtaskPart {
    pub fn new(id: String, session_id: String, message_id: String, r#type: TypeEnum, prompt: String, description: String, agent: String) -> SubtaskPart {
        SubtaskPart {
            id,
            session_id,
            message_id,
            r#type,
            prompt,
            description,
            agent,
            model: None,
            command: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "subtask")]
    Subtask,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Subtask
    }
}

