/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubtaskPartInput {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "prompt")]
    pub prompt: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "agent")]
    pub agent: String,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::SessionPromptRequestModel>>,
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl SubtaskPartInput {
    pub fn new(r#type: Type, prompt: String, description: String, agent: String) -> SubtaskPartInput {
        SubtaskPartInput {
            id: None,
            r#type,
            prompt,
            description,
            agent,
            model: None,
            command: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "subtask")]
    Subtask,
}

impl Default for Type {
    fn default() -> Type {
        Self::Subtask
    }
}

