/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SymbolLocation {
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "range")]
    pub range: Box<models::Range>,
}

impl SymbolLocation {
    pub fn new(uri: String, range: models::Range) -> SymbolLocation {
        SymbolLocation {
            uri,
            range: Box::new(range),
        }
    }
}

