/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Symbol {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: f64,
    #[serde(rename = "location")]
    pub location: Box<models::SymbolLocation>,
}

impl Symbol {
    pub fn new(name: String, kind: f64, location: models::SymbolLocation) -> Symbol {
        Symbol {
            name,
            kind,
            location: Box::new(location),
        }
    }
}

