/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Todo {
    /// Brief description of the task
    #[serde(rename = "content")]
    pub content: String,
    /// Current status of the task: pending, in_progress, completed, cancelled
    #[serde(rename = "status")]
    pub status: String,
    /// Priority level of the task: high, medium, low
    #[serde(rename = "priority")]
    pub priority: String,
}

impl Todo {
    pub fn new(content: String, status: String, priority: String) -> Todo {
        Todo {
            content,
            status,
            priority,
        }
    }
}

