/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStateCompleted {
    #[serde(rename = "status")]
    pub status: StatusEnum,
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "output")]
    pub output: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "time")]
    pub time: Box<models::ToolStateCompletedTime>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::FilePart>>,
}

impl ToolStateCompleted {
    pub fn new(status: StatusEnum, input: std::collections::HashMap<String, serde_json::Value>, output: String, title: String, metadata: std::collections::HashMap<String, serde_json::Value>, time: models::ToolStateCompletedTime) -> ToolStateCompleted {
        ToolStateCompleted {
            status,
            input,
            output,
            title,
            metadata,
            time: Box::new(time),
            attachments: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEnum {
    #[serde(rename = "completed")]
    Completed,
}

impl Default for StatusEnum {
    fn default() -> StatusEnum {
        Self::Completed
    }
}

