/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolListItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "parameters", deserialize_with = "Option::deserialize")]
    pub parameters: Option<serde_json::Value>,
}

impl ToolListItem {
    pub fn new(id: String, description: String, parameters: Option<serde_json::Value>) -> ToolListItem {
        ToolListItem {
            id,
            description,
            parameters,
        }
    }
}

