/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolStatePending {
    #[serde(rename = "status")]
    pub status: StatusEnum,
    #[serde(rename = "input")]
    pub input: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "raw")]
    pub raw: String,
}

impl ToolStatePending {
    pub fn new(status: StatusEnum, input: std::collections::HashMap<String, serde_json::Value>, raw: String) -> ToolStatePending {
        ToolStatePending {
            status,
            input,
            raw,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEnum {
    #[serde(rename = "pending")]
    Pending,
}

impl Default for StatusEnum {
    fn default() -> StatusEnum {
        Self::Pending
    }
}

