/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TuiSelectSessionRequest {
    /// Session ID to navigate to
    #[serde(rename = "sessionID")]
    pub session_id: String,
}

impl TuiSelectSessionRequest {
    pub fn new(session_id: String) -> TuiSelectSessionRequest {
        TuiSelectSessionRequest {
            session_id,
        }
    }
}

