/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnknownErrorData {
    #[serde(rename = "message")]
    pub message: String,
}

impl UnknownErrorData {
    pub fn new(message: String) -> UnknownErrorData {
        UnknownErrorData {
            message,
        }
    }
}

