/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VcsInfo {
    #[serde(rename = "branch")]
    pub branch: String,
}

impl VcsInfo {
    pub fn new(branch: String) -> VcsInfo {
        VcsInfo {
            branch,
        }
    }
}

