/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WellKnownAuth {
    #[serde(rename = "type")]
    pub r#type: TypeEnum,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "token")]
    pub token: String,
}

impl WellKnownAuth {
    pub fn new(r#type: TypeEnum, key: String, token: String) -> WellKnownAuth {
        WellKnownAuth {
            r#type,
            key,
            token,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypeEnum {
    #[serde(rename = "wellknown")]
    Wellknown,
}

impl Default for TypeEnum {
    fn default() -> TypeEnum {
        Self::Wellknown
    }
}

