/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorktreeResetInput {
    #[serde(rename = "directory")]
    pub directory: String,
}

impl WorktreeResetInput {
    pub fn new(directory: String) -> WorktreeResetInput {
        WorktreeResetInput {
            directory,
        }
    }
}

