/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Worktree {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "directory")]
    pub directory: String,
}

impl Worktree {
    pub fn new(name: String, branch: String, directory: String) -> Worktree {
        Worktree {
            name,
            branch,
            directory,
        }
    }
}

