/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Workspace {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "branch", deserialize_with = "Option::deserialize")]
    pub branch: Option<String>,
    #[serde(rename = "projectID")]
    pub project_id: String,
    #[serde(rename = "config")]
    pub config: Box<models::ExperimentalWorkspaceCreateRequestConfig>,
}

impl Workspace {
    pub fn new(id: String, branch: Option<String>, project_id: String, config: models::ExperimentalWorkspaceCreateRequestConfig) -> Workspace {
        Workspace {
            id,
            branch,
            project_id,
            config: Box::new(config),
        }
    }
}

