/*
 * opencode
 *
 * opencode api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorktreeCreateInput {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Additional startup script to run after the project's start command
    #[serde(rename = "startCommand", skip_serializing_if = "Option::is_none")]
    pub start_command: Option<String>,
}

impl WorktreeCreateInput {
    pub fn new() -> WorktreeCreateInput {
        WorktreeCreateInput {
            name: None,
            start_command: None,
        }
    }
}

